# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDHAlertView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod ‘DHAlertView’

  # Pods for TestDHAlertView

  target 'TestDHAlertViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDHAlertViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
